#!/usr/bin/env bash

unset CDPATH
umask 0077

if [[ "${USER}" ]]; then
  mkdir -p "${HOME}/Workspace/vms" \
    "${HOME}/Workspace/volumes" \
    "${HOME}/Workspace/repos/github/${USER}" \
    "${HOME}/Workspace/repos/gitlab/${USER}" \
    "${HOME}/Documents" \
    "${HOME}/Downloads" \
    "${HOME}/Music" \
    "${HOME}/Pictures" \
    "${HOME}/Private" \
    "${HOME}/Public" \
    "${HOME}/Videos"
fi

for entry in "${PWD}"/dot/*; do
  cd "${entry}" && ./setup
  cd - || return
done

