#!/usr/bin/env bash

os=linux
arch=amd64
file="$(
  curl -sSL "https://golang.org/dl/?mode=json" \
    | grep -o '[^"]*'${os}'-'${arch}'.tar.gz' \
    | head -n 1
)"

mkdir -p "${HOME}/.local/share" "${HOME}/.local/bin"
rm -rf "${HOME}/.local/share/go"

curl -L "https://go.dev/dl/${file}" > "${HOME}/.local/share/${file}"
tar -C "${HOME}/.local/share" -xzf "${HOME}/.local/share/${file}"
ln -sf "${HOME}/.local/share/go/bin/go" "${HOME}/.local/bin/go"
ln -sf "${HOME}/.local/share/go/bin/gofmt" "${HOME}/.local/bin/gofmt"
rm -rf "${HOME}/.local/share/${file}"

