#!/usr/bin/env bash

if [[ -r "$1" ]]; then
  [[ -n "$(command -v pbcopy)" ]] && exec pbcopy < "$1"
  [[ -n "$(command -v xclip)" ]] && exec xclip < "$1"
fi

[[ -n "$(command -v pbcopy)" ]] && exec pbcopy <<< "$1"
[[ -n "$(command -v xclip)" ]] && exec xclip <<< "$1"

