#!/usr/bin/env bash

cd "${CORE}"

case "$1" in
  vi*) exec vi "${HOME}/.core/dot/vim/vimrc" ;;
  tm*) exec vi "${HOME}/.core/dot/tmux/tmux.conf" ;;
  ba*) exec vi "${HOME}/.core/dot/shell/bashrc" ;;
  al*) exec vi "${HOME}/.core/dot/alacritty/alacritty.yml" ;;
  ssh) exec vi "${HOME}/.ssh/config" ;;
esac

cd -
