#!/usr/bin/env bash

echo "Vim cheatsheet

[c,v,d,y][a,i][b,B,f,p,w,W]
---------------------------
b   - ()
B   - {}
f   - function
p   - paragraph
w   - word
W   - word (can contain punctuation)
viw - select inner word
viW - select inner word (can contain punctuation)
vip - select inner paragraph
vif - select inner function
vib - select inner block wih ()
viB - select inner block with {}

Extras
------
.    - repeat last command
;    - repeat last f/F/t/T action forward
,    - repeat last f/F/t/T action backwards
}    - jump to next paragraph
{    - jump to previous paragraph
I    - insert at the beginning of the line
o    - append (open) a new line below the current line
O    - append (open) a new line above the current line
ea   - append to word
s    - delete character and substitute text
S    - delete line and substitute text (same as cc)
cc   - change (replace) entire line
c$   - change (replace) to the end of the line
fx   - jump to next occurrence of character x
tx   - jump to one character before the character x
xp   - transpose two letters (delete and paste)
<ip  - unindent paragraph
>ip  - indent paragraph
!ip  - send paragraph to shell command
gq   - wrap selected lines
gqap - wrap around paragraph
gqip - wrap paragraph
nG   - go to line number n
zj   - jump to next fold
zk   - jump to previous fold
za   - toggle fold under cursor
zo   - open fold under cursor
zO   - open fold under cursor recursively
zc   - close fold under cursor
zC   - close fold under cursor recursively
zR   - open all folds
zM   - close all folds
zj   - move cursor to next fold
zk   - move cursor to previous fold
C-[FBUD] - forward/back, up/down"
